# DO NOT EDIT THIS FILE!
#
# Python module Img__POA generated by omniidl

import omniORB
omniORB.updateModule("Img__POA")

# ** 1. Stub files contributing to this module
import Img_idl

# ** 2. Sub-modules

# ** 3. End
