# DO NOT EDIT THIS FILE!
#
# Python module ObjectRecognition__POA generated by omniidl

import omniORB
omniORB.updateModule("ObjectRecognition__POA")

# ** 1. Stub files contributing to this module
import ObjectRecognition_idl

# ** 2. Sub-modules

# ** 3. End
