# DO NOT EDIT THIS FILE!
#
# Python module Img generated by omniidl

import omniORB
omniORB.updateModule("Img")

# ** 1. Stub files contributing to this module
import Img_idl

# ** 2. Sub-modules

# ** 3. End
